<?php

require_once('DatabaseHelper.php');

$database = new DatabaseHelper();

$filmname  = '';
if(isset($_GET['film_search_name'])){
    $filmname = $_GET['film_search_name'];
}

$filmdauer  = '';
if(isset($_GET['film_search_dauer'])){
    $filmdauer = $_GET['film_search_dauer'];
}

$filmgenre  = '';
if(isset($_GET['film_search_genre'])){
    $filmgenre = $_GET['film_search_genre'];
}

$filmjahr  = '';
if(isset($_GET['film_search_jahr'])){
    $filmjahr = $_GET['film_search_jahr'];
}

$get_filme_array = $database->selectAllFilms($filmname, $filmdauer, $filmgenre, $filmjahr);
?>

<html>

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>

<body>

<h1>Filme Crud</h1>
<br>

<h2>Add Film: </h2>
<form method="post" action="addFilm.php">
    <!-- ID is not needed, because its autogenerated by the database -->

    <!-- Name textbox -->
    <div>
        <label for="new_name">Film name:</label>
        <input id="new_name" name="film_name_af" type="text" maxlength="20">
    </div>
    <br>

    <!-- Surname textbox -->
    <div>
        <label for="new_dauer">Dauer in min:</label>
        <input id="new_dauer" name="dauer_min" type="number">
    </div>
    <br>

    <div>
        <label for="new_genre">Genre:</label>
        <input id="new_genre" name="film_genre" type="text" maxlength="20">
    </div>
    <br>

    <div>
        <label for="new_jahr">Erscheinungsjahr:</label>
        <input id="new_jahr" name="new_jahr" type="number" min="1930">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit" class="btn btn-outline-success">
            Add Film
        </button>
    </div>
</form>
<br>
<hr>

<!-- Delete Person -->
<h2>Delete Film: </h2>
<form method="post" action="delFilm.php">
    <!-- ID textbox -->
    <div>
        <label for="del_name">Filmname:</label>
        <input id="del_name" name="delete_film_name" type="text" maxlength="30">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit" class="btn btn-outline-danger">
            Delete Film
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search form -->
<h2>Film Search:</h2>
<form method="get">
    <!-- ID textbox:-->
    <div>
        <label for="FilmName">Filmname:</label>
        <input id="FilmName" name="film_search_name" type="text" value='<?php echo $filmname; ?>' >
    </div>
    <br>

    <!-- Name textbox:-->
    <div>
        <label for="dauer_film">Dauer in min:</label>
        <input id="dauer_film" name="film_search_dauer" type="number"  value='<?php echo $filmdauer; ?>'
               maxlength="20">
    </div>
    <br>

    <!-- Surname textbox:-->
    <div>
        <label for="genre_film">Genre:</label>
        <input id="genre_film" name="film_search_genre" type="text" maxlength="20"
               value='<?php echo $filmgenre; ?>'>
    </div>
    <br>

    <div>
        <label for="jahr_film">Erscheinungsjahr:</label>
        <input id="jahr_film" name="film_search_jahr" type="number"
               value='<?php echo $filmjahr; ?>'>
    </div>
    <br>


    <!-- Submit button -->
    <div>
        <button id='submit' type='submit' class="btn btn-outline-success">
            Search Film
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search result -->
<h2>Film Search Result:</h2>
<div class="mx-3 mt-3">
    <table class="table mt-3">
        <thead>
        <tr>
            <th class="table-column-25">
                <div class="header" data-column-index="0">
                    <span class="pull-left">Filmname</span>
                </div>
            </th>
            <th class="table-column-25">
                <div class="header" data-column-index="1">
                    <span class="pull-left">Dauer</span>
                </div>
            </th>
            <th class="table-column-25">
                <div class="header" data-column-index="1">
                    <span class="pull-left">Genre</span>
                </div>
            </th>
            <th class="table-column-25">
                <div class="header" data-column-index="1">
                    <span class="pull-left">Erscheinungsjahr</span>
                </div>
            </th>
        </tr>
        </thead>
        <?php foreach ($get_filme_array as $element) : ?>
            <tbody>
            <tr>
                <td><?php echo $element['NAME']; ?>  </td>
                <td><?php echo $element['DAUER']." min"; ?>  </td>
                <td><?php echo $element['GENRE']; ?>  </td>
                <td><?php echo $element['ERCHEINUNGSJAHR']; ?>  </td>

            </tr>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
<br>
<hr>



<h2>Update Film: </h2>
<form method="post" action="updateFilm.php">
    <!-- ID textbox -->
    <div>
        Film:
        <select name = "film_name_update">
            <option value = "">---Select---</option>
            <?php foreach ($get_filme_array as $filme) : ?>
                <option value = "<?php echo $filme['NAME'] ?>"><?php echo $filme['NAME'] ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <br>


    <div>
        <label for="neue_dauer">Neue Dauer:</label>
        <input id="neue_dauer" name="film_dauer_update" type="number" max="200" min="60">
    </div>
    <br>

    <div>
        <label for="neues_genre">Genre Update:</label>
        <input id="neues_genre" name="film_genre_update" type="text" maxlength="30">
    </div>
    <br>

    <div>
        <label for="neues_jahr">Neues Jahr:</label>
        <input id="neues_jahr" name="film_jahr_update" type="number" min="1900" max="2022">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit"  class="btn btn-outline-success">
            Update Film
        </button>
    </div>
    <br>
</form>
<br>


<br>
<a href="index.php">
    go back to main page
</a>

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</body>
</html>
