<?php

require_once('DatabaseHelper.php');

$database = new DatabaseHelper();

$film_kt = '';
if(isset($_GET['film_search_kt'])){
    $film_kt = $_GET['film_search_kt'];
}
$filiale_id_kt = '';
if(isset($_GET['filiale_search_kt'])){
    $filiale_id_kt = $_GET['filiale_search_kt'];
}
$saal_kt = '';
if(isset($_GET['saal_search_kt'])){
    $saal_kt = $_GET['saal_search_kt'];
}
$kunden_id_kt = '';
if(isset($_GET['kunden_nr_kt'])){
    $kunden_id_kt = $_GET['kunden_nr_kt'];
}
$datum_kt = '';
if(isset($_GET['datum_search_kt'])){
    $datum_kt = $_GET['datum_search_kt'];
}
$anfang_kt = '';
if(isset($_GET['anfang_search_kt'])){
    $anfang_kt = $_GET['anfang_search_kt'];
}


$kaufen_ticket_array = $database->selectAllKaufenTicket($film_kt, $filiale_id_kt, $saal_kt, $kunden_id_kt, $datum_kt, $anfang_kt);
$kino_array = $database->getAllCinemas();
$wird_abgespielt_array = $database->selectAllWirdAbgespielt('', '', '', '', '');
$kunden_array = $database->selectAllPersons('','','');

?>

<html>

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>

<body>

<h1>Kaufen Ticket Crud</h1>
<br>

<!-- ticket kaufen -->
<h2>Add kaufen ticket: </h2>
<form method="post" action="addKaufenTicket.php">
    <!-- ID is not needed, because its autogenerated by the database -->

    <!-- Name textbox -->
    <div>
        Select Kunde:
        <select name = "kunden_id_kt">
            <option value = "">---Select---</option>
            <?php foreach ($kunden_array as $kunde) : ?>
                <option value = "<?php echo $kunde['KUNDENNR'] ?>"><?php echo $kunde['KUNDENNR'] ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <br>

    <!-- Surname textbox -->
    <div>
        Select film:
        <select name = "kaufen_ticket_film">
            <option value = "">---Select---</option>
            <?php foreach ($wird_abgespielt_array as $film) : ?>
                <option value = "<?php echo $film['FILMNAME'] ?>"><?php echo $film['FILMNAME'] ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <br>

    Filiale:
    <select name = "filiale_id_kt">
        <option value = "">---Select---</option>
        <?php foreach ($kino_array as $kino) : ?>
            <option value = "<?php echo $kino['FILIALEID'] ?>"><?php echo $kino['FILIALEID'] ?></option>
        <?php endforeach; ?>
    </select>
    <br>
    <br>

    <div>
        <label for="saal_id_kt">Saal Nr.:</label>
        <input id="saal_id_kt" name="saal_id_kt" type="number" min="1" max="4">
    </div>
    <br>

    <div>
        <label for="datum_ka">Datum (YYYY-MM-DD):</label>
        <input id="datum_ka" name="datum_kt" type="text" maxlength="11">
    </div>
    <br>

    <div>
        <label for="begin_ka">Beginn: </label>
        <input id="begin_ka" name="spielzeit_kt" type="text" maxlength="5">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit" class="btn btn-outline-success">
            Ticket kaufen
        </button>
    </div>
</form>
<br>
<hr>


<h2>Kaufen Ticket Search:</h2>
<form method="get">
    <!-- ID textbox:-->
    <div>
        <label for="film_search_kt">Film Name:</label>
        <input id="film_search_kt" name="film_search_kt" type="text" maxlength="25"
               value='<?php echo $film_kt; ?>'>
    </div>
    <br>

    <div>
        <label for="filiale_search_kt">FilialeID:</label>
        <input id="filiale_search_kt" name="filiale_search_kt" type="number" value='<?php echo $filiale_id_kt; ?>' min="1" max="6">
    </div>
    <br>

    <div>
        <label for="saal_search_kt">Saal Nr.:</label>
        <input id="saal_search_kt" name="saal_search_kt" type="number" value='<?php echo $saal_kt; ?>' min="1" max="4">
    </div>
    <br>



    <div>
        <label for="date_search_kt">Datum:</label>
        <input id="date_search_kt" name="date_search_kt" type="text" maxlength="10"
               value='<?php echo $datum_kt; ?>'>
    </div>
    <br>

    <div>
        <label for="anfang_search_wa">Beginn:</label>
        <input id="anfang_search_wa" name="anfang_search_kt" type="text" maxlength="5"
               value='<?php echo $anfang_kt; ?>'>
    </div>
    <br>

    <div>
        <label for="kunden_nr_kt">Kunden Nr.:</label>
        <input id="kunden_nr_kt" name="kunden_nr_kt" type="number" min="1"
               value='<?php echo $kunden_id_kt; ?>'>
    </div>
    <br>


    <!-- Submit button -->
    <div>
        <button id='submit' type='submit' class="btn btn-outline-primary">
            Search
        </button>
    </div>
</form>
<br>
<hr>


<h2>Delete from kaufen ticket: </h2>
<form method="post" action="delKaufenTicket.php">
    <!-- ID textbox -->
    <div>
        <label for="del_filmname">Filmname:</label>
        <input id="del_filmname" name="kt_del_filmname" type="text" maxlength="25">
    </div>
    <br>
    <div>
        <label for="del_filiale">Filiale:</label>
        <input id="del_filiale" name="kt_del_filiale" type="number" min="7" max="13">
    </div>
    <br>

    <div>
        <label for="del_saal">Saal:</label>
        <input id="del_saal" name="kt_del_saal" type="number" min="1" max="4">
    </div>
    <br>

    <div>
        <label for="del_datum">Datum (YYYY-MM-DD):</label>
        <input id="del_datum" name="kt_del_datum" type="text" maxlength="10">
    </div>
    <br>

    <div>
        <label for="del_uhrzeit">Uhrzeit:</label>
        <input id="del_uhrzeit" name="kt_del_begin" type="text" maxlength="10">
    </div>
    <br>

    <div>
        <label for="del_kunde">KundenNr:</label>
        <input id="del_kunde" name="kt_del_kunden" type="number" min="1">
    </div>
    <br>


    <!-- Submit button -->
    <div>
        <button type="submit" class="btn btn-outline-danger">
            Delete entry
        </button>
    </div>
</form>
<br>
<hr>





<h2>Update Kunde Kaufen Ticket: </h2>
<form method="post" action="kaufenTicketUpdate.php">
    <!-- ID textbox -->
    <div>
        Film:
        <select name = "film_name_update">
            <option value = "">---Select---</option>
            <?php foreach ($kaufen_ticket_array as $filme) : ?>
                <option value = "<?php echo $filme['FILM'] ?>"><?php echo $filme['FILM'] ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <br>

    <div>
        <label for="kunden_nr">Kunden Nr.:</label>
        <input id="kunden_nr" name="kunde_update" type="number" min="1">
    </div>
    <br>

    <div>
        <label for="datum_up">Datum(YYYY-MM-DD):</label>
        <input id="datum_up" name="datum_update" type="text" maxlength="10">
    </div>
    <br>

    <div>
        <label for="anfang">Beginn:</label>
        <input id="angang" name="begin_update" type="text" >
    </div>
    <br>

    <div>
        <label for="neue_kn">Neue Kunden Nr.:</label>
        <input id="neue_kn" name="neue_kunden_nr" type="number" min="1">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit"  class="btn btn-outline-success">
            Update Ticket
        </button>
    </div>
    <br>
</form>
<br>







<h2>Gekaufte tickets:</h2>
<div class="mx-3 mt-3">
    <table class="table mt-3">
        <thead>
        <tr>
            <th class="table-column-25">
                <div class="header" data-column-index="0">
                    <span class="pull-left">Film</span>
                </div>
            </th>
            <th class="table-column-25">
                <div class="header" data-column-index="0">
                    <span class="pull-left">Filiale</span>
                </div>
            </th>
            <th class="table-column-25">
                <div class="header" data-column-index="1">
                    <span class="pull-left">Saal Nr</span>
                </div>
            </th>
            <th class="table-column-25">
                <div class="header" data-column-index="1">
                    <span class="pull-left">Kunden Nr.</span>
                </div>
            </th>
            <th class="table-column-25">
                <div class="header" data-column-index="1">
                    <span class="pull-left">Datum</span>
                </div>
            </th>
            <th class="table-column-25">
                <div class="header" data-column-index="1">
                    <span class="pull-left">Beginn</span>
                </div>
            </th>
        </tr>
        </thead>
        <?php foreach ($kaufen_ticket_array as $element) : ?>
            <tbody>
            <tr>
                <td><?php echo $element['FILM']?> </td>
                <td><?php echo $element['FILIALEID']; ?>  </td>
                <td><?php echo $element['SAAL']; ?>  </td>
                <td><?php echo $element['KUNDENNR']; ?>  </td>
                <td><?php echo $element['DATUM']; ?>  </td>
                <td><?php echo $element['ANFANG']; ?>  </td>
            </tr>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
<br>
<hr>



<br>
<a href="index.php">
    go back to main page
</a>

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</body>
</html>