<?php

require_once('DatabaseHelper.php');

$database = new DatabaseHelper();

$kunden_id = '';
if (isset($_GET['Kunden_id'])) {
    $kunden_id = $_GET['Kunden_id'];
}

$kunden_name = '';
if (isset($_GET['kunden_name'])) {
    $kunden_name = $_GET['kunden_name'];
}

$alter = '';
if (isset($_GET['kunden_alter'])) {
    $alter = $_GET['kunden_alter'];
}

$person_array = $database->selectAllPersons($kunden_id, $kunden_name, $alter);

?>


<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>

<body>
<h1>KundeIn Crud</h1>
<br>

<h2>Add KundeIn: </h2>
<form method="post" action="addPerson.php">
    <!-- ID is not needed, because its autogenerated by the database -->

    <!-- Name textbox -->
    <div>
        <label for="new_name">Name:</label>
        <input id="new_name" name="name" type="text" maxlength="20">
    </div>
    <br>

    <!-- Surname textbox -->
    <div>
        <label for="new_alter">Alter:</label>
        <input id="new_alter" name="alter" type="number">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit" class="btn btn-outline-success">
            Add Person
        </button>
    </div>
</form>
<br>
<hr>
<!-- Delete Person -->
<h2>Delete KundeIn: </h2>
<form method="post" action="delPerson.php">
    <!-- ID textbox -->
    <div>
        <label for="del_id">ID:</label>
        <input id="del_id" name="delete_kunde_id" type="number" min="0">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit"  class="btn btn-outline-danger">
            Delete Person
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search form -->
<h2>KundeIn Search:</h2>
<form method="get">
    <!-- ID textbox:-->
    <div>
        <label for="Kunden_id">ID:</label>
        <input id="Kunden_id" name="Kunden_id" type="number" value='<?php echo $kunden_id; ?>' min="1">
    </div>
    <br>

    <!-- Name textbox:-->
    <div>
        <label for="name">Name:</label>
        <input id="name" name="kunden_name" type="text" value='<?php echo $kunden_name; ?>'
               maxlength="20">
    </div>
    <br>

    <!-- Surname textbox:-->
    <div>
        <label for="alter">Alter:</label>
        <input id="alter" name="kunden_alter" type="number"
               value='<?php echo $alter; ?>'>
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button id='submit' type='submit'  class="btn btn-outline-info">
            Search
        </button>
    </div>
</form>
<br>
<hr>



<h2>Update KundeIn: </h2>
<form method="post" action="updateKunde.php">
    <!-- ID textbox -->
    <div>
        <label for="update_id">ID von Kunden zum Verbessern:</label>
        <input id="update_id" name="id_kunde_update" type="number" min="0">
    </div>
    <br>


    <div>
        <label for="neuer_name">Neuer Name:</label>
        <input id="neuer_name" name="kunde_name_neu" type="text" maxlength="20">
    </div>
    <br>

    <div>
        <label for="neues_alter">Neues Alter:</label>
        <input id="neues_alter" name="kunde_alter_neu" type="number" min="3">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit"  class="btn btn-outline-success">
            Update Kunde
        </button>
    </div>
    <br>
</form>
    <br>


<h2>KundeIn Search Result:</h2>
<div class="mx-3 mt-3">
    <table class="table mt-3">
        <thead>
        <tr>
            <th class="table-column-25">
                <div class="header" data-column-index="0">
                    <span class="pull-left">ID</span>
                </div>
            </th>
            <th class="table-column-25">
                <div class="header" data-column-index="1">
                    <span class="pull-left">Name</span>
                </div>
            </th>
            <th class="table-column-25">
                <div class="header" data-column-index="1">
                    <span class="pull-left">Alter</span>
                </div>
            </th>
        </tr>
        </thead>
        <?php foreach ($person_array as $person) : ?>
            <tbody>
            <tr>
                <td><?php echo $person['KUNDENNR']; ?>  </td>
                <td><?php echo $person['NAME']; ?>  </td>
                <td><?php echo $person['KUNDENALTER']; ?>  </td>
            </tr>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
<br>
<hr>


<a href="index.php">
    go back to main page
</a>
<br>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</body>

</html>